name: Notificación DevOps ITLA

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a ntfy.sh
        run: |
          curl -H "Title: Nuevo push a main" \
               -H "Priority: high" \
               -d "Se ha subido código a la rama main del repositorio hola-mundo-ci" \
               https://ntfy.sh/devops-itla
